name: Ci

on:
  push:
    branches:
      - nix

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-build-aarch64:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        extra-conf: |
          extra-platforms = aarch64-linux
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: >
          nix run github:nix-community/nix-eval-jobs
          -- --gc-roots-dir gcroot
          --flake
          ".#packages.aarch64-linux"
    - run: >
          nix run github:Mic92/nix-fast-build
          -- --skip-cached --no-nom
          --systems aarch64-linux
          --flake
          ".#packages.aarch64-linux"
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        nix build .#packages.aarch64-linux.mainnet
        docker load < result
        docker tag mainnet:nix ghcr.io/cronos-labs/external-node:mainnet-v24.9.0-aarch64
        docker push ghcr.io/cronos-labs/external-node:mainnet-v24.9.0-aarch64
        docker manifest create --amend ghcr.io/cronos-labs/external-node:mainnet-v24.9.0 ghcr.io/cronos-labs/mainnet-v24.9.0-aarch64
        docker manifest push ghcr.io/cronos-labs/external-node:mainnet-v24.9.0

  nix-build-amd64:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: >
          nix run github:nix-community/nix-eval-jobs
          -- --gc-roots-dir gcroot
          --flake
          ".#packages.x86_64-linux"
    - run: >
          nix run github:Mic92/nix-fast-build
          -- --skip-cached --no-nom
          --systems x86_64-linux
          --flake
          ".#packages.x86_64-linux"
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        nix build .#packages.x86_64-linux.mainnet
        docker load < result
        docker tag mainnet:nix ghcr.io/cronos-labs/external-node:mainnet-v24.9.0-amd64
        docker push ghcr.io/cronos-labs/external-node:mainnet-v24.9.0-amd64
        docker manifest create --amend ghcr.io/cronos-labs/external-node:mainnet-v24.9.0 ghcr.io/cronos-labs/mainnet-v24.9.0-amd64
        docker manifest push ghcr.io/cronos-labs/external-node:mainnet-v24.9.0
